Transform: 'AWS::Serverless-2016-10-31'
Description: Sorting Visualizer API
Resources:
  sort:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: io.projects.sortingapi.StreamLambdaHandler::handleRequest
      Runtime: java11
      Description: Java function
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active