name: AWS Deployment

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    branches:
      - main
      - "feature/*"
    types:
      - completed

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build
      - run: |
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name sorting-api \
            --region us-east-1 \
            --debug
