name: CI/CD Pipeline
on:
  push:
    branches:
      - "master"
      - "feature/*"
  pull_request:
    branches:
      - "master"
jobs:
  build-and-test:
    name: Maven Clean Install
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      - name: Run mvn command
        run: mvn -B clean install
  deploy-to-aws:
    needs: build-and-test
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Run Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          terraform init
          terraform plan
